# NOTE One more date first_day_of_year is added
# in draw_all_daily_charts by default. Don't add it here.

from typing import Dict, List

ticker_anchors: Dict[str, List[str]] = {
    "9022.T": [],
    "AAPL": [],
    "ADM": [],
    "AMZN": [],
    "ARKK": [],
    "BTU": [],
    "CIB": [],
    "COPX": [],
    "COST": [],
    "CPER": [],
    "DBA": [],
    "DBC": [],
    "EC": [],
    "EWJ": [],
    "EWW": [],
    "EWZ": [],
    "FCX": [],
    "FXI": [],
    "GEO": [],
    "GLD": [],
    "GLNCY": [],
    "GPRK": [],
    "GRNT": [],
    "HRL": [],
    "IGIC": [],
    "IWM": [],
    "KRE": [],
    "MLPD.MI": [],
    "MSFT": [],
    "NE": [],
    "NVDA": [],
    "QQQ": [],
    "SBUX": [],
    "SDZ.SW": [],
    "SLV": [],
    "SMH": [],
    "SPY": [],
    "STLA": [],
    "TECK": [],
    "TLT": [],
    "VNQ": [],
    "XBI": [],
    "XHB": [],
    "XLE": [],
    "XLP": [],
    "XME": [],
}
